// Mocks generated by Mockito 5.4.2 from annotations
// in todo_mobile_app/test/features/todo_list/domain/usecases/add_task_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_mobile_app/features/todo_list/domain/entities/tasks.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Tasks].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasks extends _i1.Mock implements _i2.Tasks {
  MockTasks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
      ) as int);
  @override
  set id(int? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set title(String? title) => super.noSuchMethod(
        Invocation.setter(
          #title,
          title,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: '',
      ) as String);
  @override
  set description(String? description) => super.noSuchMethod(
        Invocation.setter(
          #description,
          description,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: '',
      ) as String);
  @override
  set dueDate(DateTime? dueDate) => super.noSuchMethod(
        Invocation.setter(
          #dueDate,
          dueDate,
        ),
        returnValueForMissingStub: null,
      );
  @override
  DateTime get dueDate => (super.noSuchMethod(
        Invocation.getter(#dueDate),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#dueDate),
        ),
      ) as DateTime);
  @override
  set status(bool? status) => super.noSuchMethod(
        Invocation.setter(
          #status,
          status,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: false,
      ) as bool);
  @override
  void markCompleted() => super.noSuchMethod(
        Invocation.method(
          #markCompleted,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
